import os
import re
from pathlib import Path

import yaml

from config.confluence_url import normalize_confluence_rest_api_url


def _env_strip(name: str) -> str | None:
    v = os.environ.get(name)
    if v is None:
        return None
    s = v.strip()
    return s if s else None


def _require_env(name: str) -> str:
    v = _env_strip(name)
    if not v:
        raise RuntimeError(
            f"Missing required environment variable {name}. "
            "Set it in CI or your shell before running the publisher."
        )
    return v


def _validate_config(cfg: dict) -> None:
    space = cfg.get("confluence_space", "")
    if space and not re.match(r'^[A-Za-z0-9_~]+$', str(space)):
        raise ValueError(
            f"Invalid confluence_space value: {space!r}. "
            "Space keys must contain only letters, digits, underscores, or tildes."
        )
    parent_id = cfg.get("confluence_parent_page_id")
    if parent_id is not None and not str(parent_id).isdigit():
        raise ValueError(
            f"Invalid confluence_parent_page_id value: {parent_id!r}. Must be a positive integer."
        )


def getConfig():
    config_path = Path(__file__).resolve().parent / "config.yaml"
    cfg = {}
    if config_path.is_file():
        with open(config_path, "r", encoding="utf-8") as yamlFileConfig:
            loaded = yaml.safe_load(yamlFileConfig)
            if isinstance(loaded, dict):
                cfg = loaded

    # Support the historical typo key for backward compatibility with existing config files.
    if "counfluence_parent_page_id" in cfg and "confluence_parent_page_id" not in cfg:
        cfg["confluence_parent_page_id"] = cfg.pop("counfluence_parent_page_id")
    else:
        cfg.pop("counfluence_parent_page_id", None)

    if cfg.get("confluence_url"):
        cfg["confluence_url"] = normalize_confluence_rest_api_url(cfg["confluence_url"])

    # --- Environment overrides / container-only config (no bundled YAML) ---

    url = _env_strip("CONFLUENCE_URL")
    if url:
        cfg["confluence_url"] = normalize_confluence_rest_api_url(url)

    space = _env_strip("CONFLUENCE_SPACE")
    if space:
        cfg["confluence_space"] = space

    parent = _env_strip("CONFLUENCE_PARENT_PAGE_ID")
    if parent:
        cfg["confluence_parent_page_id"] = int(parent)

    banner_repo = _env_strip("BANNER_REPO_URL")
    if banner_repo:
        cfg["banner_repo_url"] = banner_repo

    banner_project = _env_strip("BANNER_PROJECT_NAME")
    if banner_project:
        cfg["banner_project_name"] = banner_project

    md_root = _env_strip("PUBLISHER_MARKDOWN_ROOT")
    if md_root:
        cfg["github_folder_with_md_files"] = md_root

    img_root = _env_strip("PUBLISHER_IMAGES_ROOT")
    if img_root:
        cfg["github_folder_with_image_files"] = img_root

    prop_key = _env_strip("PUBLISHER_PROPERTY_KEY")
    if prop_key:
        cfg["publisher_property_key"] = prop_key

    legacy = _env_strip("CONFLUENCE_LEGACY_SEARCH_PATTERN")
    if legacy is not None:
        cfg["confluence_search_pattern"] = legacy

    # When no config.yaml (e.g. Docker image), everything comes from env + defaults below.
    if not config_path.is_file():
        cfg["confluence_url"] = normalize_confluence_rest_api_url(
            _require_env("CONFLUENCE_URL")
        )
        cfg["confluence_space"] = _require_env("CONFLUENCE_SPACE")
        cfg["confluence_parent_page_id"] = int(_require_env("CONFLUENCE_PARENT_PAGE_ID"))
        cfg.setdefault("github_folder_with_md_files", "./data")
        cfg.setdefault("github_folder_with_image_files", "./data_images")
        cfg.setdefault("banner_repo_url", "https://github.com")
        cfg.setdefault("banner_project_name", "My project")
        cfg.setdefault("publisher_property_key", "autogenerated-publisher")
        cfg.setdefault("confluence_search_pattern", "")

    _validate_config(cfg)
    return cfg
