import html
import json
import logging

import requests
from requests.auth import HTTPBasicAuth

from config.getconfig import getConfig
from confluence_api_models import (
    AttachmentResponse,
    CreatedPageResponse,
    ParentPageResponse,
    SearchResponse,
    validate_response_payload,
)

CONFIG = getConfig()

PUBLISHER_PROPERTY_VALUE = {"publisher": "github-confluence-publisher"}


def _confluence_request_error_message(response, context):
    snippet = (response.text or "")[:500].strip()
    if snippet.startswith("<!DOCTYPE") or snippet.startswith("<html"):
        return (
            f"{context}: received HTML instead of JSON (status {response.status_code}). "
            "Check confluence_url in publisher/config/config.yaml — it must be the REST API base, "
            "e.g. https://your-site.atlassian.net/wiki/rest/api/ (not the wiki space URL)."
        )
    return f"{context}: HTTP {response.status_code} — {snippet}"


def _json_from_response(response, context):
    try:
        return response.json()
    except ValueError:
        raise RuntimeError(_confluence_request_error_message(response, context)) from None


def _banner_html():
    repo_url = str(CONFIG.get("banner_repo_url") or "https://github.com").strip()
    project = str(CONFIG.get("banner_project_name") or "My project").strip()
    safe_url = html.escape(repo_url, quote=True)
    safe_project = html.escape(project, quote=True)
    return (
        f'<p style="background-color:#e7be17;">This page is autogenerated. '
        f'Make changes in the GitHub repository: '
        f'<b><a href="{safe_url}">{safe_project}</a></b></p>'
    )


def _set_page_property(page_id, login, password):
    """Tag a page with the publisher content property (Confluence REST)."""
    key = str(CONFIG.get("publisher_property_key") or "autogenerated-publisher").strip()
    url = f"{CONFIG['confluence_url']}content/{page_id}/property"
    payload = {"key": key, "value": PUBLISHER_PROPERTY_VALUE}
    logging.debug("Setting content property on page %s key=%s", page_id, key)
    response = requests.post(
        url=url,
        json=payload,
        auth=HTTPBasicAuth(login, password),
        headers={"Content-Type": "application/json"},
    )
    if response.status_code not in (200, 201):
        raise RuntimeError(_confluence_request_error_message(response, "Set page property failed"))


def verify_parent_page_exists(login, password):
    """
    Fail fast with a clear error if the configured parent page or API URL is wrong.
    Uses the same auth as page creation (email + API token as password for Cloud).
    """
    parent_id = CONFIG["counfluence_parent_page_id"]
    url = f"{CONFIG['confluence_url']}content/{parent_id}?expand=space"
    logging.debug("Verifying parent page URL: " + url)
    response = requests.get(url, auth=HTTPBasicAuth(login, password), timeout=60)
    if response.status_code == 404:
        raise RuntimeError(
            f"Parent page id {parent_id} was not found at the Confluence REST API. "
            "Confirm counfluence_parent_page_id in config.yaml matches the numeric id in the page URL, "
            "and that confluence_url points to your site's /wiki/rest/api/ base."
        )
    if response.status_code >= 400:
        raise RuntimeError(_confluence_request_error_message(response, "Failed to load parent page"))
    data = _json_from_response(response, "Failed to parse parent page response")
    validated = validate_response_payload(data, ParentPageResponse, "Failed to parse parent page response")
    space_key = validated.space.key if validated.space else None
    if space_key and space_key != CONFIG["confluence_space"]:
        logging.warning(
            "Parent page is in space %r but config confluence_space is %r — "
            "createPage may fail unless they match.",
            space_key,
            CONFIG["confluence_space"],
        )


def createPage(title, content, parentPageID, login, password):
    newPageJSONQueryString = """
    {
        "type": "page",
        "title": "DEFAULT PAGE TITLE",
        "ancestors": [
            {
            "id": 111
            }
        ],
        "space": {
            "key": "DEFAULT KEY"
        },
        "body": {
            "storage": {
                "value": "DEFAULT PAGE CONTENT",
                "representation": "storage"
            }
        }
    }
    """

    newPagejsonQuery = json.loads(newPageJSONQueryString)

    newPagejsonQuery["space"]["key"] = CONFIG["confluence_space"]

    if parentPageID is None:
        newPagejsonQuery["ancestors"][0]["id"] = CONFIG["counfluence_parent_page_id"]
    else:
        newPagejsonQuery["ancestors"][0]["id"] = str(parentPageID)

    newPagejsonQuery["title"] = title
    newPagejsonQuery["body"]["storage"]["value"] = _banner_html() + content

    logging.info("Create new page: " + newPagejsonQuery["title"])
    logging.debug("with content: " + newPagejsonQuery["body"]["storage"]["value"])
    logging.debug(json.dumps(newPagejsonQuery, indent=4, sort_keys=True))

    logging.debug("Calling URL: " + str(CONFIG["confluence_url"]) + "content/")

    response = requests.post(
        url=CONFIG["confluence_url"] + "content/",
        json=newPagejsonQuery,
        auth=HTTPBasicAuth(login, password),
        timeout=120,
    )

    logging.debug(response.status_code)
    if response.status_code == 200:
        logging.info("Created successfully")
    else:
        raise RuntimeError(_confluence_request_error_message(response, "Create page failed"))
    payload = _json_from_response(response, "Create page failed")
    validated = validate_response_payload(payload, CreatedPageResponse, "Create page failed")
    logging.debug(json.dumps(payload, indent=4, sort_keys=True))

    _set_page_property(validated.id, login, password)

    logging.debug("Returning created page id: " + validated.id)
    return validated.id


def _search_pages_cql(cql, login, password):
    base = CONFIG["confluence_url"].rstrip("/") + "/"
    response = requests.get(
        base + "search",
        params={"cql": cql, "limit": 1000},
        auth=HTTPBasicAuth(login, password),
        timeout=120,
    )
    logging.debug(response.status_code)
    if response.status_code >= 400:
        raise RuntimeError(_confluence_request_error_message(response, "Search failed"))
    results = _json_from_response(response, "Search failed")
    validated = validate_response_payload(results, SearchResponse, "Search failed")
    logging.debug(json.dumps(results, indent=4, sort_keys=True))

    found_pages = []
    for result in validated.results:
        found_pages.append(result.content.id)
        logging.info("Found page: " + result.content.id + " with title: " + result.content.title)

    return found_pages


def searchPages(login, password):
    space = str(CONFIG["confluence_space"]).strip()
    parent_id = CONFIG["counfluence_parent_page_id"]
    prop_key = str(CONFIG.get("publisher_property_key") or "autogenerated-publisher").strip()

    key_lit = json.dumps(prop_key)
    cql_prop = (
        f'type = page AND space = "{space}" AND ancestor = {parent_id} '
        f"AND content.property[{key_lit}]"
    )
    logging.debug("Property-based CQL: %s", cql_prop)

    found_pages = _search_pages_cql(cql_prop, login, password)

    if not found_pages:
        legacy_pattern = str(CONFIG.get("confluence_search_pattern") or "").strip()
        if legacy_pattern:
            cql_legacy = (
                f'text~{{"{legacy_pattern}"}} AND type = page AND space = "{space}" '
                f"AND ancestor = {parent_id}"
            )
            logging.debug("Legacy text-based CQL: %s", cql_legacy)
            legacy_ids = _search_pages_cql(cql_legacy, login, password)
            if legacy_ids:
                logging.warning(
                    "Found %d page(s) via legacy title/text search; they will be deleted and "
                    "recreated with content-property tagging.",
                    len(legacy_ids),
                )
                found_pages = legacy_ids

    logging.debug(
        "Found pages in space %s under parent %s: %s",
        space,
        parent_id,
        found_pages,
    )

    return found_pages


def deletePages(pagesIDList, login, password):
    deletedPages = []

    for page in pagesIDList:
        logging.info("Delete page: " + str(page))
        logging.debug("Calling URL: " + str(CONFIG["confluence_url"]) + "content/" + str(page))
        response = requests.delete(
            url=str(CONFIG["confluence_url"]) + "content/" + str(page),
            auth=HTTPBasicAuth(login, password),
            timeout=120,
        )
        logging.debug("Delete status code: " + str(response.status_code))
        if response.status_code == 204:
            logging.info("Deleted successfully")
        elif response.status_code == 404:
            logging.info("Page already absent (404), skipping")
        elif response.status_code >= 400:
            raise RuntimeError(_confluence_request_error_message(response, "Delete page failed"))

    return deletedPages


def attachFile(pageIdForFileAttaching, attachedFile, login, password):
    logging.debug("Calling URL: " + str(CONFIG["confluence_url"]) + "content/" + str(pageIdForFileAttaching) + "/child/attachment")

    attachedFileStructure = {"file": attachedFile}
    attachedValues = {"comment": "file was attached by the script"}
    attachedHeader = {
        "Accept": "application/json",
        "X-Atlassian-Token": "nocheck",
    }

    response = requests.post(
        url=CONFIG["confluence_url"] + "content/" + str(pageIdForFileAttaching) + "/child/attachment",
        files=attachedFileStructure,
        data=attachedValues,
        auth=HTTPBasicAuth(login, password),
        headers=attachedHeader,
        timeout=120,
    )

    logging.debug(response.status_code)
    if response.status_code == 200:
        logging.info("File was attached successfully")
        payload = _json_from_response(response, "Attach file failed")
        validated = validate_response_payload(payload, AttachmentResponse, "Attach file failed")
        logging.debug(json.dumps(payload, indent=4, sort_keys=True))

        logging.debug("Returning attached file id: " + validated.results[0].id)
        return validated.results[0].id
    else:
        logging.error("File has not attached: " + _confluence_request_error_message(response, "Attach file failed"))
        raise RuntimeError(_confluence_request_error_message(response, "Attach file failed"))
