import html
import json
import logging
import os
import re

import requests
from requests.auth import HTTPBasicAuth

from config.getconfig import getConfig
from confluence_api_models import (
    AttachmentResponse,
    CreatedPageResponse,
    ParentPageResponse,
    SearchResponse,
    validate_response_payload,
)

PUBLISHER_PROPERTY_VALUE = {"publisher": "github-confluence-publisher"}


def _confluence_request_error_message(response, context):
    snippet = (response.text or "")[:500].strip()
    if snippet.startswith("<!DOCTYPE") or snippet.startswith("<html"):
        return (
            f"{context}: received HTML instead of JSON (status {response.status_code}). "
            "Check confluence_url in publisher/config/config.yaml — it must be the REST API base, "
            "e.g. https://your-site.atlassian.net/wiki/rest/api/ (not the wiki space URL)."
        )
    return f"{context}: HTTP {response.status_code} — {snippet}"


def _json_from_response(response, context):
    try:
        return response.json()
    except ValueError:
        raise RuntimeError(_confluence_request_error_message(response, context)) from None


class ConfluenceClient:
    """Wraps Confluence REST API calls. Holds credentials and config; no module-level state."""

    def __init__(self, login: str, password: str, config: dict):
        self._auth = HTTPBasicAuth(login, password)
        self._cfg = config
        self._base = config["confluence_url"].rstrip("/") + "/"

    def _banner_html(self) -> str:
        repo_url = str(self._cfg.get("banner_repo_url") or "https://github.com").strip()
        project = str(self._cfg.get("banner_project_name") or "My project").strip()
        safe_url = html.escape(repo_url, quote=True)
        safe_project = html.escape(project, quote=True)
        return (
            f'<p style="background-color:#e7be17;">This page is autogenerated. '
            f'Make changes in the GitHub repository: '
            f'<b><a href="{safe_url}">{safe_project}</a></b></p>'
        )

    def set_page_property(self, page_id: str) -> None:
        """Tag a page with the publisher content property (Confluence REST).
        Silently succeeds if the property already exists (409 Conflict).
        """
        key = str(self._cfg.get("publisher_property_key") or "autogenerated-publisher").strip()
        url = f"{self._base}content/{page_id}/property"
        payload = {"key": key, "value": PUBLISHER_PROPERTY_VALUE}
        logging.debug("Setting content property on page %s key=%s", page_id, key)
        response = requests.post(
            url=url,
            json=payload,
            auth=self._auth,
            headers={"Content-Type": "application/json"},
            timeout=120,
        )
        if response.status_code in (200, 201):
            return
        if response.status_code == 409:
            # Property already exists from a previous run — no update needed.
            logging.debug("Content property already set on page %s", page_id)
            return
        raise RuntimeError(_confluence_request_error_message(response, "Set page property failed"))

    def verify_parent_page_exists(self) -> None:
        """Fail fast with a clear error if the configured parent page or API URL is wrong."""
        parent_id = self._cfg["confluence_parent_page_id"]
        url = f"{self._base}content/{parent_id}?expand=space"
        logging.debug("Verifying parent page URL: %s", url)
        response = requests.get(url, auth=self._auth, timeout=60)
        if response.status_code == 404:
            raise RuntimeError(
                f"Parent page id {parent_id} was not found at the Confluence REST API. "
                "Confirm confluence_parent_page_id in config.yaml matches the numeric id in the page URL, "
                "and that confluence_url points to your site's /wiki/rest/api/ base."
            )
        if response.status_code >= 400:
            raise RuntimeError(_confluence_request_error_message(response, "Failed to load parent page"))
        data = _json_from_response(response, "Failed to parse parent page response")
        validated = validate_response_payload(data, ParentPageResponse, "Failed to parse parent page response")
        space_key = validated.space.key if validated.space else None
        if space_key and space_key != self._cfg["confluence_space"]:
            logging.warning(
                "Parent page is in space %r but config confluence_space is %r — "
                "createPage may fail unless they match.",
                space_key,
                self._cfg["confluence_space"],
            )

    def _find_page_by_title(self, title: str, parent_id) -> dict | None:
        """Return {id, version} for a direct child page with the given title, or None."""
        safe_title = title.replace('\\', '\\\\').replace('"', '\\"')
        space = str(self._cfg["confluence_space"]).strip()
        cql = (
            f'type = page AND space = "{space}" '
            f'AND title = "{safe_title}" AND parent = {parent_id}'
        )
        response = requests.get(
            self._base + "search",
            params={"cql": cql, "limit": 1},
            auth=self._auth,
            timeout=30,
        )
        if response.status_code >= 400:
            return None
        results = response.json().get("results", [])
        if not results:
            return None
        page_id = str(results[0]["content"]["id"])

        # Fetch the current version number (required for PUT /content/{id}).
        ver_resp = requests.get(
            f"{self._base}content/{page_id}",
            params={"expand": "version"},
            auth=self._auth,
            timeout=30,
        )
        if ver_resp.status_code != 200:
            return None
        version = ver_resp.json().get("version", {}).get("number")
        if version is None:
            return None
        return {"id": page_id, "version": version}

    def create_page(self, title: str, content: str, parent_page_id=None) -> str:
        parent_id = parent_page_id if parent_page_id is not None else self._cfg["confluence_parent_page_id"]
        payload = {
            "type": "page",
            "title": title,
            "ancestors": [{"id": str(parent_id)}],
            "space": {"key": self._cfg["confluence_space"]},
            "body": {
                "storage": {
                    "value": self._banner_html() + content,
                    "representation": "storage",
                }
            },
        }
        logging.info("Creating page: %s", title)
        logging.debug("%s", json.dumps(payload, indent=4, sort_keys=True))

        response = requests.post(
            url=self._base + "content/",
            json=payload,
            auth=self._auth,
            timeout=120,
        )

        logging.debug(response.status_code)
        if response.status_code != 200:
            raise RuntimeError(_confluence_request_error_message(response, "Create page failed"))
        data = _json_from_response(response, "Create page failed")
        validated = validate_response_payload(data, CreatedPageResponse, "Create page failed")

        self.set_page_property(validated.id)
        logging.info("Created page: %s (id=%s)", title, validated.id)
        return validated.id

    def update_page(self, page_id: str, title: str, content: str, version: int) -> str:
        """Update an existing page to the new content. Increments the version number."""
        payload = {
            "version": {"number": version + 1},
            "title": title,
            "type": "page",
            "body": {
                "storage": {
                    "value": self._banner_html() + content,
                    "representation": "storage",
                }
            },
        }
        logging.info("Updating page: %s (id=%s, v%d→v%d)", title, page_id, version, version + 1)
        logging.debug("%s", json.dumps(payload, indent=4, sort_keys=True))

        response = requests.put(
            url=f"{self._base}content/{page_id}",
            json=payload,
            auth=self._auth,
            timeout=120,
        )

        logging.debug(response.status_code)
        if response.status_code != 200:
            raise RuntimeError(_confluence_request_error_message(response, "Update page failed"))
        data = _json_from_response(response, "Update page failed")
        validated = validate_response_payload(data, CreatedPageResponse, "Update page failed")

        self.set_page_property(validated.id)
        logging.info("Updated page: %s (id=%s)", title, validated.id)
        return validated.id

    def upsert_page(self, title: str, content: str, parent_page_id=None) -> str:
        """Create the page if it doesn't exist, update it if it does."""
        parent_id = parent_page_id if parent_page_id is not None else self._cfg["confluence_parent_page_id"]
        existing = self._find_page_by_title(title, parent_id)
        if existing:
            return self.update_page(existing["id"], title, content, existing["version"])
        return self.create_page(title, content, parent_page_id)

    def _search_pages_cql(self, cql: str) -> list[str]:
        response = requests.get(
            self._base + "search",
            params={"cql": cql, "limit": 1000},
            auth=self._auth,
            timeout=120,
        )
        logging.debug(response.status_code)
        if response.status_code >= 400:
            raise RuntimeError(_confluence_request_error_message(response, "Search failed"))
        results = _json_from_response(response, "Search failed")
        validated = validate_response_payload(results, SearchResponse, "Search failed")
        logging.debug("%s", json.dumps(results, indent=4, sort_keys=True))

        found_pages = []
        for result in validated.results:
            found_pages.append(result.content.id)
            logging.info("Found page: %s with title: %s", result.content.id, result.content.title)

        return found_pages

    def _has_publisher_property(self, page_id: str, prop_key: str) -> bool:
        """Return True if the page has the publisher content property set."""
        url = f"{self._base}content/{page_id}/property/{prop_key}"
        response = requests.get(url, auth=self._auth, timeout=30)
        return response.status_code == 200

    def search_pages(self) -> list[str]:
        space = str(self._cfg["confluence_space"]).strip()
        parent_id = self._cfg["confluence_parent_page_id"]
        prop_key = str(self._cfg.get("publisher_property_key") or "autogenerated-publisher").strip()

        # Fetch all descendant pages with a simple CQL, then filter by content property.
        # content.property CQL syntax is unreliable across Confluence Cloud versions.
        cql_all = f'type = page AND space = "{space}" AND ancestor = {parent_id}'
        logging.debug("Fetching all descendant pages with CQL: %s", cql_all)
        all_pages = self._search_pages_cql(cql_all)

        found_pages = [pid for pid in all_pages if self._has_publisher_property(pid, prop_key)]
        logging.debug("Pages with publisher property: %s", found_pages)

        if not found_pages:
            legacy_pattern = str(self._cfg.get("confluence_search_pattern") or "").strip()
            if legacy_pattern:
                cql_legacy = (
                    f'text~{{"{legacy_pattern}"}} AND type = page AND space = "{space}" '
                    f"AND ancestor = {parent_id}"
                )
                logging.debug("Legacy text-based CQL: %s", cql_legacy)
                legacy_ids = self._search_pages_cql(cql_legacy)
                if legacy_ids:
                    logging.warning(
                        "Found %d page(s) via legacy title/text search; they will be deleted and "
                        "recreated with content-property tagging.",
                        len(legacy_ids),
                    )
                    found_pages = legacy_ids

        logging.debug(
            "Found pages in space %s under parent %s: %s",
            space,
            parent_id,
            found_pages,
        )

        return found_pages

    def delete_pages(self, page_ids: list[str]) -> list[str]:
        deleted = []
        for page_id in page_ids:
            logging.info("Delete page: %s", page_id)
            logging.debug("Calling URL: %scontent/%s", self._base, page_id)
            response = requests.delete(
                url=f"{self._base}content/{page_id}",
                auth=self._auth,
                timeout=120,
            )
            logging.debug("Delete status code: %s", response.status_code)
            if response.status_code == 204:
                logging.info("Deleted successfully")
                deleted.append(page_id)
            elif response.status_code == 404:
                logging.info("Page already absent (404), skipping")
            elif response.status_code >= 400:
                raise RuntimeError(_confluence_request_error_message(response, "Delete page failed"))
        return deleted

    def _get_attachment_id(self, page_id: str, filename: str) -> str | None:
        """Return the ID of an existing attachment with the given filename, or None."""
        response = requests.get(
            f"{self._base}content/{page_id}/child/attachment",
            params={"filename": filename},
            auth=self._auth,
            timeout=30,
        )
        if response.status_code != 200:
            return None
        results = response.json().get("results", [])
        return str(results[0]["id"]) if results else None

    def attach_file(self, page_id: str, attached_file) -> str:
        """Upload a file as a page attachment. Updates the existing attachment if one with the same name already exists."""
        filename = os.path.basename(attached_file.name)
        existing_id = self._get_attachment_id(page_id, filename)

        if existing_id:
            logging.debug("Updating existing attachment %s on page %s", filename, page_id)
            url = f"{self._base}content/{page_id}/child/attachment/{existing_id}/data"
            response = requests.post(
                url=url,
                files={"file": attached_file},
                data={"comment": "file was attached by the script"},
                auth=self._auth,
                headers={"X-Atlassian-Token": "nocheck"},
                timeout=120,
            )
        else:
            logging.debug("Creating new attachment %s on page %s", filename, page_id)
            url = f"{self._base}content/{page_id}/child/attachment"
            response = requests.post(
                url=url,
                files={"file": attached_file},
                data={"comment": "file was attached by the script"},
                auth=self._auth,
                headers={"Accept": "application/json", "X-Atlassian-Token": "nocheck"},
                timeout=120,
            )

        logging.debug(response.status_code)
        if response.status_code == 200:
            logging.info("File attached successfully: %s", filename)
            payload = _json_from_response(response, "Attach file failed")
            validated = validate_response_payload(payload, AttachmentResponse, "Attach file failed")
            logging.debug("%s", json.dumps(payload, indent=4, sort_keys=True))
            logging.debug("Returning attached file id: %s", validated.results[0].id)
            return validated.results[0].id
        else:
            msg = _confluence_request_error_message(response, "Attach file failed")
            logging.error("File has not attached: %s", msg)
            raise RuntimeError(msg)
