"""Unit tests for ConfluenceClient (property tagging, banner, search CQL)."""

from __future__ import annotations

import unittest
from unittest.mock import MagicMock, patch

import pages_controller as pc
from pages_controller import ConfluenceClient


def _make_client(cfg: dict) -> ConfluenceClient:
    return ConfluenceClient("user@example.com", "token", cfg)


class TestSetPageProperty(unittest.TestCase):
    def test_posts_json_with_configured_key(self):
        cfg = {
            "confluence_url": "https://example.com/wiki/rest/api/",
            "publisher_property_key": "my-publisher-key",
        }
        client = _make_client(cfg)
        with patch("pages_controller.requests.post") as post:
            post.return_value = MagicMock(status_code=200, text="{}")
            client.set_page_property("12345")
        post.assert_called_once()
        call_kw = post.call_args.kwargs
        self.assertIn("json", call_kw)
        self.assertEqual(
            call_kw["json"],
            {"key": "my-publisher-key", "value": pc.PUBLISHER_PROPERTY_VALUE},
        )
        self.assertTrue(call_kw["url"].endswith("content/12345/property"))

    def test_raises_on_error_status(self):
        cfg = {"confluence_url": "https://example.com/wiki/rest/api/", "publisher_property_key": "k"}
        client = _make_client(cfg)
        with patch("pages_controller.requests.post") as post:
            post.return_value = MagicMock(status_code=400, text="bad")
            with self.assertRaises(RuntimeError):
                client.set_page_property("1")

    def test_includes_timeout(self):
        cfg = {"confluence_url": "https://example.com/wiki/rest/api/", "publisher_property_key": "k"}
        client = _make_client(cfg)
        with patch("pages_controller.requests.post") as post:
            post.return_value = MagicMock(status_code=200, text="{}")
            client.set_page_property("1")
        self.assertEqual(post.call_args.kwargs.get("timeout"), 120)


class TestBannerHtml(unittest.TestCase):
    def test_default_banner(self):
        cfg = {
            "confluence_url": "https://example.com/wiki/rest/api/",
            "banner_repo_url": "https://github.com",
            "banner_project_name": "My project",
        }
        client = _make_client(cfg)
        html = client._banner_html()
        self.assertIn("https://github.com", html)
        self.assertIn("My project", html)
        self.assertNotIn("<script", html.lower())

    def test_escapes_special_chars(self):
        cfg = {
            "confluence_url": "https://example.com/wiki/rest/api/",
            "banner_repo_url": 'https://ex.com/a?x=1&y=2"',
            "banner_project_name": 'Foo <bar>',
        }
        client = _make_client(cfg)
        html_out = client._banner_html()
        self.assertNotIn("<bar>", html_out)
        self.assertIn("Foo &lt;bar&gt;", html_out)


class TestSearchPages(unittest.TestCase):
    def test_returns_pages_with_publisher_property(self):
        cfg = {
            "confluence_url": "https://x/wiki/rest/api/",
            "confluence_space": "SPC",
            "confluence_parent_page_id": 99,
            "publisher_property_key": "autogenerated-publisher",
        }
        client = _make_client(cfg)
        with patch.object(client, "_search_pages_cql", return_value=["a", "b"]) as cql:
            with patch.object(client, "_has_publisher_property", return_value=True):
                ids = client.search_pages()
        self.assertEqual(ids, ["a", "b"])
        self.assertEqual(cql.call_count, 1)
        cql_arg = cql.call_args_list[0][0][0]
        self.assertIn('space = "SPC"', cql_arg)
        self.assertIn("ancestor = 99", cql_arg)
        # Should NOT use content.property CQL (unreliable on Cloud)
        self.assertNotIn("content.property", cql_arg)

    def test_filters_out_pages_without_property(self):
        cfg = {
            "confluence_url": "https://x/wiki/rest/api/",
            "confluence_space": "SPC",
            "confluence_parent_page_id": 99,
            "publisher_property_key": "autogenerated-publisher",
        }
        client = _make_client(cfg)
        with patch.object(client, "_search_pages_cql", return_value=["a", "b", "c"]):
            with patch.object(client, "_has_publisher_property", side_effect=[True, False, True]):
                ids = client.search_pages()
        self.assertEqual(ids, ["a", "c"])


class TestSetPagePropertyTolerates409(unittest.TestCase):
    def test_409_does_not_raise(self):
        cfg = {"confluence_url": "https://example.com/wiki/rest/api/", "publisher_property_key": "k"}
        client = _make_client(cfg)
        with patch("pages_controller.requests.post") as post:
            post.return_value = MagicMock(status_code=409, text="conflict")
            client.set_page_property("1")  # should not raise


class TestUpsertPage(unittest.TestCase):
    def _base_cfg(self):
        return {
            "confluence_url": "https://example.com/wiki/rest/api/",
            "confluence_space": "SPC",
            "confluence_parent_page_id": 99,
            "publisher_property_key": "k",
            "banner_repo_url": "https://github.com",
            "banner_project_name": "Test",
        }

    def test_creates_when_page_does_not_exist(self):
        client = _make_client(self._base_cfg())
        with patch.object(client, "_find_page_by_title", return_value=None):
            with patch.object(client, "create_page", return_value="new-id") as create:
                result = client.upsert_page("My Page", "<p>content</p>", parent_page_id=99)
        create.assert_called_once_with("My Page", "<p>content</p>", 99)
        self.assertEqual(result, "new-id")

    def test_updates_when_page_exists(self):
        client = _make_client(self._base_cfg())
        with patch.object(client, "_find_page_by_title", return_value={"id": "existing-id", "version": 3}):
            with patch.object(client, "update_page", return_value="existing-id") as update:
                result = client.upsert_page("My Page", "<p>new</p>", parent_page_id=99)
        update.assert_called_once_with("existing-id", "My Page", "<p>new</p>", 3)
        self.assertEqual(result, "existing-id")

    def test_update_page_increments_version(self):
        client = _make_client(self._base_cfg())
        with patch("pages_controller.requests.put") as put:
            put.return_value = MagicMock(
                status_code=200,
                text='{"id":"42"}',
                json=lambda: {"id": "42"},
            )
            with patch.object(client, "set_page_property"):
                client.update_page("42", "Title", "<p>body</p>", version=5)
        payload = put.call_args.kwargs["json"]
        self.assertEqual(payload["version"]["number"], 6)


class TestDeletePages(unittest.TestCase):
    def test_returns_deleted_ids(self):
        cfg = {"confluence_url": "https://example.com/wiki/rest/api/"}
        client = _make_client(cfg)
        with patch("pages_controller.requests.delete") as delete:
            delete.return_value = MagicMock(status_code=204)
            result = client.delete_pages(["1", "2"])
        self.assertEqual(result, ["1", "2"])

    def test_skips_already_absent_pages(self):
        cfg = {"confluence_url": "https://example.com/wiki/rest/api/"}
        client = _make_client(cfg)
        with patch("pages_controller.requests.delete") as delete:
            delete.return_value = MagicMock(status_code=404)
            result = client.delete_pages(["1"])
        self.assertEqual(result, [])


if __name__ == "__main__":
    unittest.main()
