"""Unit tests for pagesController (property tagging, banner, search CQL)."""

from __future__ import annotations

import unittest
from unittest.mock import MagicMock, patch

import pagesController as pc


class TestSetPageProperty(unittest.TestCase):
    def test_posts_json_with_configured_key(self):
        cfg = {
            "confluence_url": "https://example.com/wiki/rest/api/",
            "publisher_property_key": "my-publisher-key",
        }
        with patch.object(pc, "CONFIG", cfg):
            with patch("pagesController.requests.post") as post:
                post.return_value = MagicMock(status_code=200, text="{}")
                pc._set_page_property("12345", "user@example.com", "token")
        post.assert_called_once()
        call_kw = post.call_args.kwargs
        self.assertIn("json", call_kw)
        self.assertEqual(
            call_kw["json"],
            {"key": "my-publisher-key", "value": pc.PUBLISHER_PROPERTY_VALUE},
        )
        self.assertTrue(call_kw["url"].endswith("content/12345/property"))

    def test_raises_on_error_status(self):
        cfg = {"confluence_url": "https://example.com/wiki/rest/api/", "publisher_property_key": "k"}
        with patch.object(pc, "CONFIG", cfg):
            with patch("pagesController.requests.post") as post:
                post.return_value = MagicMock(status_code=400, text="bad")
                with self.assertRaises(RuntimeError):
                    pc._set_page_property("1", "u", "p")


class TestBannerHtml(unittest.TestCase):
    def test_default_banner(self):
        cfg = {"banner_repo_url": "https://github.com", "banner_project_name": "My project"}
        with patch.object(pc, "CONFIG", cfg):
            html = pc._banner_html()
        self.assertIn("https://github.com", html)
        self.assertIn("My project", html)
        self.assertNotIn("<script", html.lower())

    def test_escapes_special_chars(self):
        cfg = {
            "banner_repo_url": 'https://ex.com/a?x=1&y=2"',
            "banner_project_name": 'Foo <bar>',
        }
        with patch.object(pc, "CONFIG", cfg):
            html_out = pc._banner_html()
        self.assertNotIn("<bar>", html_out)
        self.assertIn("Foo &lt;bar&gt;", html_out)


class TestSearchPages(unittest.TestCase):
    def test_property_search_only_when_results(self):
        cfg = {
            "confluence_url": "https://x/wiki/rest/api/",
            "confluence_space": "SPC",
            "counfluence_parent_page_id": 99,
            "publisher_property_key": "autogenerated-publisher",
            "confluence_search_pattern": "(legacy)",
        }
        with patch.object(pc, "CONFIG", cfg):
            with patch("pagesController._search_pages_cql", side_effect=[["a", "b"], []]) as cql:
                ids = pc.searchPages("u", "p")
        self.assertEqual(ids, ["a", "b"])
        self.assertEqual(cql.call_count, 1)
        prop_arg = cql.call_args_list[0][0][0]
        self.assertIn('space = "SPC"', prop_arg)
        self.assertIn("ancestor = 99", prop_arg)
        self.assertIn("content.property", prop_arg)
        self.assertIn("autogenerated-publisher", prop_arg)
        self.assertIn("github-confluence-publisher", prop_arg)
        self.assertIn(".value", prop_arg)

    def test_legacy_fallback_when_empty(self):
        cfg = {
            "confluence_url": "https://x/wiki/rest/api/",
            "confluence_space": "SPC",
            "counfluence_parent_page_id": 1,
            "publisher_property_key": "k",
            "confluence_search_pattern": "oldpat",
        }
        with patch.object(pc, "CONFIG", cfg):
            with patch("pagesController._search_pages_cql", side_effect=[[], ["z"]]) as cql:
                ids = pc.searchPages("u", "p")
        self.assertEqual(ids, ["z"])
        self.assertEqual(cql.call_count, 2)


if __name__ == "__main__":
    unittest.main()
